---

language: node_js
node_js:
  - node

addons:
  code_climate:
    repo_token:
      secure: "3e3fa36281cf47c17ed3cd63f42162290efb928dbd0477b684780609316260d6"

before_script:
  - npm install codeclimate-test-reporter istanbul -g

script:
  - istanbul cover npm run test
  - make lint
  - make test

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info